# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: starcoin/sirius:buildv2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4096m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew --no-daemon dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew unitTest --stacktrace --continue --no-daemon --max-workers 2

      - run:
          name: Save test results
          command: |
            mkdir -p ~/artifacts/test-results/unit/
            find . -type f -regex ".*/build/test-results/unitTest/.*xml" -exec cp {} ~/artifacts/test-results/unit/ \;
          #TODO report  cp -r build/reports/integrationTests ~/artifacts/reports/
          when: always

      - store_test_results:
          path: ~/artifacts/test-results/unit

      - store_artifacts:
          path: ~/artifacts